#pragma once

enum class Token { KEYWORD = 0, SYMBOL, IDENTIFIER, INT_CONST, STRING_CONST, NONE };
enum class Keyword { CLASS = 0, METHOD, FUNCTION, CONSTRUCTOR, INT, BOOLEAN, CHAR, VOID, VAR, STATIC, FIELD, LET, DO, IF, ELSE, WHILE, RETURN, TRUE, FALSE, K_NULL, THIS, NONE };
enum class Status { OK, NOT_FOUND, SYNTAX_ERROR };